### ISSUE TITLE
ModuleNotFoudError have occurred

### ISSUE THREAD

**Issue by pandanoir** [online-judge-tools/oj#763]
I have updated online-judge-tools to v10.0.2.

```
$ pip3 install online-judge-tools
```

However, oj command exists with ModuleNotFoundError.

```
Traceback (most recent call last):
  File "/usr/local/bin/oj", line 6, in <module>
    from onlinejudge._implementation.main import main
ModuleNotFoundError: No module named 'onlinejudge._implementation.main'
```

Before the update, online-judge-tools was working fine.

# versions

* Python 3.8.2
* pip 20.0.2
* Ubuntu 20.04

**Comment by kmyk** [comment]
How do you update online-judge-tools? Please paste the entire log.
(At least, you must not use `pip3 install online-judge-tools` because `--upgrade` is required to update packages.)

As far as I guess, you installed online-judge-tools under the system directory with `sudo` at once and then update it under the home directory without `sudo`, so two versions of online-judge-tools is installed.
Just removing the entry point of the old one with `$ sudo rm /usr/local/bin/oj` will work. Or, uninstall both of them and reinstall (`$ sudo pip3 uninstall online-judge-tools online-judge-api-client`, `$ pip3 uninstall online-judge-tools online-judge-api-client`, and `$ pip3 install --user --upgrade --force-reinstall online-judge-tools`)

**Comment by pandanoir** [comment]
I didn't install online-judge-tools with sudo, but force-reinstalling fixed my problem. Thanks!
